name: martix demo
on: push
jobs:
    build:
        strategy:
            matrix:
                operating-system: [ubuntu-latest, windows-latest]
                node-version: [12, 14, 16]
        runs-on: ${{matrix.operating-system}}
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: ${{matrix.node-version}}