name: Reusable Demo
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: This is the name of the reusable artifact
                required: false
                default: dist
                type: string
jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/download@v3
              with:
                name: ${{inputs.artifact-name}}
            - name: list files
              run: ls
            - name: Output information
              run: echo 'Deploying & Uploading'
